stages:
  - build
  - upload

variables:
  ZIP_FILE: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}.zip"
  RCLONE_CONFIG: "/tmp/rclone.conf"

before_script:
  - apk update && apk add zip rclone

build_zip:
  stage: build
  script:
    - echo "Zipping the repository, excluding .git and hidden files/folders..."
    - zip -r "${ZIP_FILE}" . --exclude ".*" --exclude ".*/**" --exclude ".git/**"
  artifacts:
    paths:
      - "${ZIP_FILE}"

upload_to_r2:
  stage: upload
  script:
    - |
      echo "Creating rclone configuration file..."
      cat <<EOF > $RCLONE_CONFIG
      [r2]
      type = s3
      provider = Cloudflare
      access_key_id = $R2_ACCESS_KEY_ID
      secret_access_key = $R2_SECRET_ACCESS_KEY
      endpoint = $R2_ENDPOINT
      EOF
    - echo "Uploading zip file to Cloudflare R2..."
    - rclone copy ${ZIP_FILE} r2:${R2_BUCKET}
  dependencies:
    - build_zip
  only:
    - tags

