stages:
  - build
  - release

variables:
  ZIP_FILE: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}.zip"

build_zip:
  stage: build
  script:
    - echo "Zipping the repository..."
    - zip -r "${ZIP_FILE}" .
  artifacts:
    paths:
      - "${ZIP_FILE}"

release:
  stage: release
  script:
    - echo "Creating a release..."
    - curl --header "PRIVATE-TOKEN: $GITLAB_PRIVATE_TOKEN" --data "name=Release $CI_COMMIT_REF_NAME" --data "tag_name=$CI_COMMIT_REF_NAME" --data "ref=$CI_COMMIT_SHA" --data "description=Release of version $CI_COMMIT_REF_NAME" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/releases"
    - echo "Uploading the zip file to the release..."
    - curl --header "PRIVATE-TOKEN: $GITLAB_PRIVATE_TOKEN" --upload-file "${ZIP_FILE}" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/uploads"
  only:
    - tags

