name: Deploy to Cloudflare R2

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install zip and rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y zip rclone

      - name: Zip repository
        run: |
          echo "Zipping the repository, excluding .git and hidden files/folders..."
          zip -r ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip . -x ".*" -x ".*/**" -x ".git/**"
        env:
          ZIP_FILE: ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip

      - name: Configure rclone
        run: |
          echo "[r2]" > /tmp/rclone.conf
          echo "type = s3" >> /tmp/rclone.conf
          echo "provider = Cloudflare" >> /tmp/rclone.conf
          echo "access_key_id = ${{ secrets.r2.R2_ACCESS_KEY_ID }}" >> /tmp/rclone.conf
          echo "secret_access_key = ${{ secrets.r2.R2_SECRET_ACCESS_KEY }}" >> /tmp/rclone.conf
          echo "bucket = ${{ vars.r2.R2_BUCKET }}" >> /tmp/rclone.conf

      - name: Upload to Cloudflare R2
        run: |
          echo "Uploading to Cloudflare R2..."
          rclone copy ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip r2:${{ vars.r2.R2_BUCKET }} --config /tmp/rclone.conf -vv --dump-bodies --retries 1 || echo "Upload failed with exit code $?"
        env:
          ZIP_FILE: ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip

      - name: Post to Discord
        if: success()
        run: |
          FILE_URL="${{ secrets.r2.R2_ENDPOINT }}/${{ vars.r2.R2_BUCKET }}/${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip"
          echo "Posting to Discord..."
          curl -H "Content-Type: application/json" -d "{\"content\": \"New release available: $FILE_URL\"}" ${{ secrets.r2.DISCORD_WEBHOOK_URL }}
