name: Deploy to Cloudflare R2

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install zip and rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y zip rclone

      - name: Zip repository
        run: |
          echo "Zipping the repository, excluding .git and hidden files/folders..."
          zip -r ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip . -x ".*" -x ".*/**" -x ".git/**"
        env:
          ZIP_FILE: ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip

      - name: Configure rclone
        run: |
          echo -e "[r2]\ntype = s3\nprovider = Cloudflare\naccess_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}\nsecret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}\nendpoint = ${{ secrets.R2_ENDPOINT }}\nno_check_bucket = true" > /tmp/rclone.conf

      - name: Test rclone configuration
        run: |
          echo "Testing rclone configuration..."
          rclone lsd r2:${{ secrets.R2_BUCKET }} --config /tmp/rclone.conf || echo "Listing directories failed as expected due to no_check_bucket"
        env:
          R2_BUCKET: ${{ secrets.R2_BUCKET }}

      - name: Upload to Cloudflare R2
        run: |
          rclone copy ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip r2:${{ secrets.R2_BUCKET }} --config /tmp/rclone.conf
        env:
          ZIP_FILE: ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip
          R2_BUCKET: ${{ secrets.R2_BUCKET }}

      - name: Post to Discord
        run: |
          FILE_URL="${{ secrets.R2_ENDPOINT }}/${{ secrets.R2_BUCKET }}/${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip"
          echo "Posting to Discord..."
          curl -H "Content-Type: application/json" -d "{\"content\": \"New release available: $FILE_URL\"}" ${{ secrets.DISCORD_WEBHOOK_URL }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
